name: Update
on:
  push:
    branches:
      - main
    
jobs:
  rate:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - uses: Swatinem/rust-cache@v1


      - name: Update the rate dataset
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: -p rates

      - name: Update the graph
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: -p graph

      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Push
        run: |
          test -z "$(git status --porcelain)" && exit 0
          git add .
          git commit -m "Update dataset and graph" -m "Updates the rate dataset and the graph with new values."
          git push origin main
